### ISSUE TITLE
プロトタイプ

### ISSUE THREAD

**Issue by koudaiii** [wantedly/risu#4]
## risu flow
1. masterがMergeされたらwebhookを受ける(POST: /builds)
2. Rails アプリを `git clone|pull`
3. S3 (or else) から前回の bundle install tarball を risu ホストに落としてくる
4. ^ の tarball を展開
5. `docker build`
   - 3. で展開した中身も含めて `COPY`
   - `bundle package -j4`
6. 1. で作った Docker image を quay.io (or else) に push
7. `docker run wantedly/wantedly rake assets:precompile`
8. `docker run ...` でコンテナ内の `vendor/bundle` を risu ホストに tarball で固める
   - ^ で固めた tarball を S3 (or else) にアップロード

S3 に上げなくとも、ホストに置いとくだけでいいかもしれない。
- S3 に置いとくと、risu サーバはスポットインスタンスを使える
#### Description

イメージのビルドを行う
#### Response

status: 200
body: start build
#### Description

ビルドの状況の一覧
#### Request Parameter

status: 200
body:  status: [ bulding | succeeded | failed ]
#### Response

build status

```
[Client]                  [risu]
   |                        |
   |----- POST /build ----->|
   |<------ "start build" -------|
   |                        |
=========== Building ============
   |                        |
   |---- GET /build/status --->| (if building)
   |<----- "building" ------|
   |                        |
   |---- GET /build/status --->| (if build was succeeded)
   |<----- "succeeded" -----|
   |                        |
   |---- GET /build/staus --->| (if build was failed)
   |<------ "failed" -------|
   |                        |   
```

**Comment by creasty** [comment]
AA でシーケンス図！w

**Comment by koudaiii** [comment]
https://github.com/wantedly/infrastructure/issues/301

こっちで管理することにするため一旦Close
